# Build settings
permalink   : /post/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/post/page/:num/"
comments: true

#source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# baseurl: ""
baseurl: "/blog"

# Site settings
title: 꿔니 블로그

# google_analytics: UA-52446115-1
#repo: http://github.com/nandomoreirame/end2end
#disqus_shortname: "fernandomoreira"
#disqus_site_shortname: "fernandomoreira"

# Author settings
author:
  name      : Yi Hyeon Kwon
  job       : Frontend Engineer
  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb     : /images/author.jpg
  email     : fides4u@gmail.com
#  url       : http://nandomoreira.me
  github    : http://github.com/kkwoni
#  twitter   : http://twitter.com/nandomoreirame
  pinterest   : http://kr.pinterest.com/yihyeonkwon
  facebook  : https://www.facebook.com/yihyeon.kwon
#  linkedin  : http://linkedin.com/in/nandomoreirame

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: post
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]


# SEO settings
#title: end2end
#description: "A free Jekyll theme for download"
#keywords: "Jekyll, theme, free, download, SEO, post, web"
#url: http://nandomoreira.me
# SEO settings ==========